### ISSUE TITLE
save the drawing into database

### ISSUE THREAD

**Issue by balasmeh** [dev-labs-bg/geofencing#3]
can you please sir explain how to save the circle into database?

**Comment by jordan-enev** [comment]
Hello,

First of all, in the repo, I just showed how we can implement drawing on a Leaflet map in React, without using any third-party drawing plugins. In the [plugin's README](https://github.com/dev-labs-bg/geofencing#installation), I summarized why I implemented it in such a way.

However, I would suggest you to use [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw/blob/develop/docs/examples/full.html) official Leaflet plugin for drawing. Here's [a working example](http://leaflet.github.io/Leaflet.draw/docs/examples/full.html).

Keep in mind that in both implementations, saving the database is not part of the libraries. You have to manually trigger the API request when the drawing is completed.
